### PR TITLE
Try to remove explicit python dependency

### PR DESCRIPTION
**Pull request by timkpaine**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by timkpaine** [comment]
@conda-forge-admin please rerender

**Comment by whitequark** [comment]
I'm not sure why my review is requested here?

**Comment by timkpaine** [comment]
> I'm not sure why my review is requested here?

it happens automatically, you can ignore

**Comment by timkpaine** [comment]
Screenshot 2023-08-11 at 12 50 04

it can be noisy over here, feel free to do the complete "ignore"

**Pull request merged**
